### PR TITLE
Updated mod for 1.17.1

### PR DESCRIPTION
**Pull request by VoltixIGS**
Updated the mod for working in 1.17.1

### CODE REVIEW

**Comment by PokeyManatee4** [comment]
Bruh I did This Before You @VoltixIGS https://sdk.bitmoji.com/render/panel/b6d0de0a-0762-418e-9db2-b84c3ef51251-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1

**Comment by PokeyManatee4** [comment]
bitmoji Bruh I Did This Before You @VoltixIGS

**Comment by VoltixIGS** [comment]
@PokeyManatee4 this is not a race, i just did a pull request to help the community get the mod simply

**Comment by NotAika** [comment]
Please stop, I'm not ready for the mod to updated at all yet. You all will get the mod in 1.18.0, when core mods are published and I make some changes.

Please people, be patient. This just further demotivates me from wanting to work on this mod :/

**Comment by PokeyManatee4** [comment]
Bruh

**Pull request closed without merging**
